### PR TITLE
Added uniform inflow ADM example

### PR DESCRIPTION
**Pull request by tonyinme**
This adds an example of the actuator disk model using uniform inflow.

### CODE REVIEW

**Comment by ewquon** [comment]
This case was successfully run by @Prabs8815 resolving issue #71, so I'm merging this in.

**Comment by Bartdoekemeijer** [comment]
FYI, you can find our example cases for SOWFA here: 
https://github.com/TUDelft-DataDrivenControl/SOWFA/tree/master/exampleCases

**Comment by Prabs8815** [comment]
dear @Bartdoekemeijer  and @ewquon  thanks again for sharing your repositories. I have a general question, how does opensource work in general in research field. If someone creates a new library or class etc. and implements in openFOAM and eventually publish their work through journals. Do you think they make the code available in github after publishing it ? For eg: I am searching for implementation of Sweeped ALM (SALM) implemented in https://www.osti.gov/biblio/1352992 
Your feedback is valuable.

**Comment by Bartdoekemeijer** [comment]
@Prabs8815 Typically, researchers are encouraged to accompany their publication with the developed software solutions and datasets, though it is not obligatory. I do not see any reference to an open software repository in the article you mention. I personally have also not seen this SALM implementation in SOWFA. I suggest you reach out to the authors in the article you mentioned.

**Pull request merged**
